### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ronen** [avajs/eslint-plugin-ava#207]
I get maximum call stack size exceeded error if a source file includes certain constructs.  Culprits include:

```
const a = { ...b }
const foo = bar(<X/>)
```

Having either of these constructs in any file causes the entire `eslint` run to error out with a traceback like:

``` 
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at cloneNodeOrObject (/[...]/node_modules/espurify/lib/clone-ast.js:16:30)
    at cloneOf (/[...]/node_modules/espurify/lib/clone-ast.js:64:16)
    at cloneObject (/[...]/node_modules/espurify/lib/clone-ast.js:52:20)
    at cloneNodeOrObject (/[...]/node_modules/espurify/lib/clone-ast.js:21:14)
    at cloneOf (/[...]/node_modules/espurify/lib/clone-ast.js:64:16)
    at cloneObject (/[...]/node_modules/espurify/lib/clone-ast.js:52:20)
    at cloneNodeOrObject (/[...]/node_modules/espurify/lib/clone-ast.js:21:14)
    at cloneOf ([...]/node_modules/espurify/lib/clone-ast.js:64:16)
    at cloneObject (/[...]/node_modules/espurify/lib/clone-ast.js:52:20)
    at cloneNodeOrObject ([...]/node_modules/espurify/lib/clone-ast.js:21:14)
```
I tried removing all other eslint plugins, and stripping down to a minimal `.eslinrc.json` configuration:

```json
{
  "parser": "babel-eslint",
  "plugins": [
    "ava"
  ],
  "extends": [
    "plugin:ava/recommended"
  ]
}
```

Versions: `eslint-plugi-ava` 5.0.0, `eslint` 5.2.0,  and `babel-eslint` 8.2.6 in my package.json (and looking in `package-lock.json` I can see that `espurify` was resolved to 1.8.0).

Without `eslint-plugin-ava`, `eslint` is working fine in my setup with a handful of other plugins an extensions and with more things in `parserOptions`.  It's just when adding `eslint-plugin-ava` that `eslint` breaks for me.

Any thoughts as to what's going on?

**Comment by twada** [comment]
This problem is fixed by  [espurify 1.8.1](https://github.com/estools/espurify/blob/master/CHANGELOG.md#181-2018-07-10). Would you clean-reinstall eslint-plugin-ava again?
