### ISSUE TITLE
esm error: Identifier '__global__' has already been declared

### ISSUE THREAD

**Issue by pvdlg** [avajs/eslint-plugin-ava#210]
This issue happens when using [atom-linter-xo](https://github.com/xojs/atom-linter-xo). I open it in this repo as it seems the problem is related to `esm` which is used by this plugin.

Here is the full stacktrace:
```
Error running XO SyntaxError: Identifier '__global__' has already been declared
Referenced from: 
    at /Users/pvdlg/git/@semantic-release/gitlab/node_modules/esm/esm.js:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/esm/esm.js:1:1312)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/esm/esm.js:2:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/util.js:5:20)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/util.js:190:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/rules/assertion-arguments.js:3:14)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/rules/assertion-arguments.js:159:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at module.exports (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/import-modules/index.js:41:21)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/index.js:6:9)
    at Object.<anonymous> (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint-plugin-ava/index.js:50:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at Plugins.load (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/plugins.js:91:26)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/plugins.js:157:21)
    at loadFromDisk (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/config-file.js:506:35)
    at load (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/config-file.js:408:26)
    at Object.loadObject (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config/config-file.js:543:35)
    at new Config (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/config.js:72:46)
    at new CLIEngine (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/eslint/lib/cli-engine.js:420:23)
    at Object.module.exports.lintText (/Users/pvdlg/git/@semantic-release/semantic-release/node_modules/xo/index.js:80:17)
    at /Users/pvdlg/.atom/packages/linter-xo/lib/lint.js:48:18
    at exports.allowUnsafeNewFunction (/Users/pvdlg/.atom/packages/custom-window-title/node_modules/loophole/lib/loophole.js:25:14)
    at /Users/pvdlg/.atom/packages/linter-xo/lib/lint.js:42:5
    at <anonymous>
(anonymous) @ /Users/pvdlg/.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by sindresorhus** [comment]
// @jdalton

**Comment by jdalton** [comment]
Hi @pvdlg!

Could you provide a simple repro repo that demonstrates the issue?

**Comment by pvdlg** [comment]
Sure: https://github.com/semantic-release/gitlab.
The problem happens only in Atom with [atom-linter-xo](https://github.com/xojs/atom-linter-xo). When I run `xo` in the terminal it works fine.

I'm using Atom 1.32.1 with `atom-linter-xo` version `0.26.0`.
It might also be related to a conflict with another plugin that also uses `esm`. So if you can't reproduce, let me know, I can provide the list of Atom plugin I'm using.

**Comment by jdalton** [comment]
Ok @pvdlg!

Using `atom-linter-xo` with Atom 1.32.1 I cannot reproduce it when `semantic-release/gitlab/index.js` is opened in Atom and I cause a lint error _(it correctly identifies it)_.

><img src=https://user-images.githubusercontent.com/4303/48242701-50ca5300-e391-11e8-97de-b14c88db431d.png width=80%>

**Comment by pvdlg** [comment]
Did you run `yarn install` in the repo?
`atom-linter-xo` will use the version installed locally if there is one.
I also have `xo` installed globally (`yarn global add xo`).

**Comment by jdalton** [comment]
I did `yarn install` and then I deleted the `node_modules` folder and performed the global install. Closed Atom, opened it back up to the `index.js` and it didn't error.

The `__global__` var is private to the compiled loader code so should not run into a `Identifier '__global__' has already been declared` error which leaves me a bit confused. One thing I could see is that maybe you had a lint rule in place to fix undeclared vars and ran it accidently on your node_modules folder, which would pick it up undeclared in the `loader.js` modify the `loader.js` to fix the issue so when I then try to load it as content source and compile it adding my own `const __global__ = this` at the top it would throw the duplicate declaration error when compiled to execute.

Ensure you're not linting your `node_modules ` folder, delete it and re-install to see if that takes care of the issue.

Regardless this probably isn't an `eslint-plugin-ava` issue so it would make more sense to file the issue on `esm` to keep the noise down for other repo issue trackers.

**Comment by pvdlg** [comment]
> Ensure you're not linting your node_modules folder, delete it and re-install to see if that takes care of the issue.

`xo` excludes the `node_modules` by default. I deleted it and re-installed by the same problem happens.

> Regardless this probably isn't an eslint-plugin-ava issue so it would make more sense to file the issue on esm to keep the noise down for other repo issue trackers.

I'll close this one and open a new issue on `esm`. I'll try to gather more info before.
