### ISSUE TITLE
TypeError for function in test file

### ISSUE THREAD

**Issue by ohtake** [avajs/eslint-plugin-ava#257]
If a test file has a function, eslint-plugin-ava raises a TypeError.

```console
$ eslint test.js
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
Occurred while linting test.js:8
    at ava.merge.CallExpression.node (node_modules\eslint-plugin-ava\rules\prefer-t-regex.js:44:35)
    at node (node_modules\enhance-visitors\index.js:25:12)
    at node (node_modules\enhance-visitors\index.js:15:7)
    at listeners.(anonymous function).forEach.listener (node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
```

```js
import test from 'ava';

function f() {
  return true;
}

test('description', t => {
  t.true(f());
});
```

`package.json` and `.eslintrc.yaml`

```json
{
  "name": "eslint-ava",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "ava": "^2.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-ava": "^7.0.0"
  },
  "scripts": {
    "test": "ava test.js",
    "lint": "eslint test.js"
  }
}
```

```yaml
---
  root: true
  plugins:
    - ava
  extends:
    - "plugin:ava/recommended"
```

Node 10.15.3 on Windows 10 x64 1809

**Comment by ohtake** [comment]
Closing. Duplicates #251.
