### ISSUE TITLE
no-identical-title crashes if title is missing

### ISSUE THREAD

**Issue by ghost** [avajs/eslint-plugin-ava#317]
```js
/* eslint ava/no-identical-title: "error" */
const test = require('ava');
test(t => t.pass());
```
Running eslint on that results in:

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting hello.ava.js:3
    at isStatic (node_modules/eslint-plugin-ava/rules/no-identical-title.js:12:31)
    at node_modules/eslint-plugin-ava/rules/no-identical-title.js:35:9
    at node_modules/enhance-visitors/index.js:25:12
    at node_modules/enhance-visitors/index.js:15:7
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

**Comment by novemberborn** [comment]
Yea that shouldn't crash. Nice find.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the feedback given in https://github.com/avajs/eslint-plugin-ava/pull/318.

**Comment by novemberborn** [comment]
It also misidentifies syntax like `test.meta.file.startsWith()` as a test declaration.

**Comment by fregante** [comment]
Same exact error when using `t.true()` (without a parameter), on the file:

https://github.com/fregante/chrome-webstore-upload-cli/blob/ab45edaf6b1681c9ce50caf65acfa89ed6f66714/test/cli.js#L27

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting ./test/cli.js:22
    at booleanHandler (./node_modules/eslint-plugin-ava/rules/prefer-t-regex.js:94:35)
    at ./node_modules/eslint-plugin-ava/rules/prefer-t-regex.js:192:5
    at ./node_modules/enhance-visitors/index.js:25:12
    at ./node_modules/enhance-visitors/index.js:15:7
    at ./node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (./node_modules/eslint/lib/linter/node-event-generator.js:336:14)
```
